env:
  browser: true
  commonjs: true
  es2020: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 11
overrides:
  - files: 'test/tiddlers/**/*.js'
    env:
      jasmine: true
    plugins:
      - jasmine
    extends:
      - 'plugin:jasmine/recommended'
rules:
  spaced-comment: ["error", "always", { "markers": ["\\"] }]
  import/no-unresolved: ["error", { ignore: ['^\$:'] }]
