{ name = "tw5-gemini-plugin"
, npm_packages =
  []
}

-- Generated by https://github.com/rambler-digital-solutions/scaraplate
-- From (dirty) https://github.com/ento/tw5-plugin-template/commit/3ff278cd2d25f3b7b3c7ef9c8b5c418556b0f482  # noqa
