let
  nurPkgs = builtins.fetchTarball {
    url = "https://github.com/ento/nur-packages/archive/c7dbeaf.tar.gz";
    # nix-prefetch-url --unpack --type sha256 $url
    sha256 = "1kdylfmkcxn2ghj9c5lxsglnzliwmyl7irwrsb9zljl4isfwxbni";
  };
  # nurPkgs = ../nur-packages/default.nix;
  pkgs = import <nixpkgs> {
    config = {
      packageOverrides = pkgs: {
        nur = import nurPkgs { inherit pkgs; };
      };
    };
  };
in
pkgs.mkShell {
  buildInputs = with pkgs; [
    nodejs
    nur.tw5-devtools
    pre-commit
  ];
  shellHook = ''
    export TIDDLYWIKI_PLUGIN_PATH=$(pwd)/node_modules/tw5-atomfeed
  '';
}

# Generated by https://github.com/rambler-digital-solutions/scaraplate
# From (dirty) https://github.com/ento/tw5-plugin-template/commit/3ff278cd2d25f3b7b3c7ef9c8b5c418556b0f482  # noqa
