let
  #nurPkgs = builtins.fetchTarball {
  #  url = "https://github.com/ento/nur-packages/archive/85463ec.tar.gz";
  #  # nix-prefetch-url --unpack --type sha256 $url
  #  sha256 = "0ngikqx8kdxdldczlff5wjqc34wfqf613fy9ml7f24hnh8lsc5ga";
  #};
  nurPkgs = ../nur-packages/default.nix;
  pkgs = import <nixpkgs> {
    config = {
      packageOverrides = pkgs: {
        nur = import nurPkgs { inherit pkgs; };
      };
    };
  };
in
pkgs.mkShell {
  buildInputs = with pkgs; [
    nodejs
    nur.tw5-devtools
    pre-commit
  ];
}

# Generated by https://github.com/rambler-digital-solutions/scaraplate
# From (dirty) https://github.com/ento/tw5-plugin-template/commit/3ff278cd2d25f3b7b3c7ef9c8b5c418556b0f482  # noqa
