on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Merge master branch
      run: "git merge origin/master"
      env:
        GIT_AUTHOR_NAME: ${{ github.actor }}
        GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
      if: github.ref != 'refs/heads/master'
    - name: Install packages
      run: "npm install"
    - name: Run tests
      run: "npm test"
  pages:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: "npm install"
    - name: Build
      run: "npm run-script build"
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: index.html
        path: src/output/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./src/output
      with:
        emptyCommits: false
      if: github.ref == 'refs/heads/master'
